#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Nov 25 10:48:51 2021

@author: valerie.hellmueller

"""
# import rasterio
import numpy as np

def calculate_ndvi(red_vector, nir_vector):


    # Allow division by zero
    np.seterr(divide='ignore', invalid='ignore')

    # Calculate NDVI
    ndvi = (nir_vector.astype(float) - red_vector.astype(float)) / (nir_vector + red_vector)
    
    
    return ndvi